### ISSUE TITLE
Add vault extension method: VaultPropertyDefOperations.GetOwnerPropertyDefID

### ISSUE THREAD

**Issue by CraigHawker** [M-Files/VAF.Extensions.Community#6]
Would be a shorthand for this sort of code.

```
            // Get the owner Mandant propertyDef
            ObjType owningObjType = env.Vault.ObjectTypeOperations.GetObjectType(Configuration.Identifier.ObjectType.Mandant);
            int besitzerMandant = owningObjType.OwnerPropertyDef;

```

Should take a single integer parameter for the object type ID.

**Comment by CraigHawker** [comment]
As this could be used from the COM API (without the VAF), I have moved this across to the COM API extensions library: https://github.com/M-Files/COMAPI.Extensions.Community/issues/4

**Comment by falk-huth-ewerk** [comment]
Hi Craig,

normally I would go via aliases and MFIdentifier in Configuration but unfortunately the property alias is not editable for Owner (Mandant) in Admin Client. Perhaps this would be a good feature request because you also use the alias in meta data card configuration – or the ID if alias is not filled. Then you have the problem that you cannot transport the meta data configuration between the vaults Dev, Test, Prod. I solved this by adding temporary code like below – but how should non-programmers do that?


             /// <summary>
             /// The method, that is run when the vault goes online.
             /// </summary>
             protected override void StartApplication()
             {
                    /*
                    PropertyDefAdmin pdAdmin;

                    pdAdmin = PermanentVault.PropertyDefOperations.GetPropertyDefAdmin(1176);
                    pdAdmin.SemanticAliases = new SemanticAliasesClass() { Value = "EW.PD.Besitzer.Mitarbeiter" };
                    PermanentVault.PropertyDefOperations.UpdatePropertyDefAdmin(pdAdmin);
                    */
                    base.StartApplication();
             }

The short version would be for this example:
int besitzerMandant = env.Vault.ObjectTypeOperations.GetOwnerPropertyDef(Configuration.Identifier.ObjectType.Mandant);

I think the parameter could be integer or MFIdentifier.

Greetings,
Falk


__

Falk Huth
Product Owner ECM/DMS Practice

EWERK DIGITAL GmbH
Brühl 24, D-04109 Leipzig
P +49 341 42649 - 514
F +49 341 42649 - 98
M +49 151 53984493
F.Huth@ewerk.com
www.ewerk.com

Geschäftsführer:
Dr. Erik Wende, Hendrik Schubert, Tassilo Möschke
Registergericht: Leipzig HRB 9065

Support:
+49 341 42649 555

Zertifiziert nach:
ISO/IEC 27001:2013
DIN EN ISO 9001:2015
DIN ISO/IEC 20000-1:2011

ISAE 3402 Typ II Assessed

EWERK-Blog<https://blog.ewerk.com/> | LinkedIn<https://www.linkedin.com/company/ewerk-group> | Xing<https://www.xing.com/company/ewerk> | Twitter<https://twitter.com/EWERK_Group> | Facebook<https://de-de.facebook.com/EWERK.IT/>


Auskünfte und Angebote per Mail sind freibleibend und unverbindlich.

Disclaimer Privacy:
Der Inhalt dieser E-Mail (einschließlich etwaiger beigefügter Dateien) ist vertraulich und nur für den Empfänger bestimmt. Sollten Sie nicht der bestimmungsgemäße Empfänger sein, ist Ihnen jegliche Offenlegung, Vervielfältigung, Weitergabe oder Nutzung des Inhalts untersagt. Bitte informieren Sie in diesem Fall unverzüglich den Absender und löschen Sie die E-Mail (einschließlich etwaiger beigefügter Dateien) von Ihrem System. Vielen Dank.

The contents of this e-mail (including any attachments) are confidential and may be legally privileged. If you are not the intended recipient of this e-mail, any disclosure, copying, distribution or use of its contents is strictly prohibited, and you should please notify the sender immediately and then delete it (including any attachments) from your system. Thank you.
Von: Craig Hawker <notifications@github.com>
Gesendet: Mittwoch, 9. September 2020 10:45
An: M-Files/VAF.Extensions.Community <VAF.Extensions.Community@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [M-Files/VAF.Extensions.Community] Add vault extension method: VaultPropertyDefOperations.GetOwnerPropertyDefID (#6)


Would be a shorthand for this sort of code.

            // Get the owner Mandant propertyDef

            ObjType owningObjType = env.Vault.ObjectTypeOperations.GetObjectType(Configuration.Identifier.ObjectType.Mandant);

            int besitzerMandant = owningObjType.OwnerPropertyDef;



Should take a single integer parameter for the object type ID.

**Comment by CraigHawker** [comment]
I have closed this issue and opened it against the COM API.  Please reply there.

That said, a few comments:

- I think this should go against VaultPropertyDefOperations, rather than VaultObjectTypeOperations personally (as it should return the property definition ID).
- The UI has that limitation for owner property definitions, you're correct, but you can add an alias to the parent or child object type and retrieve the data from that using MFIdentifiers.  That's better than pushing the alias in using the API.
- If this extension method is added to the COM API then it cannot use `MFIdentifier` as that is a VAF construct.  Also: there is an implicit operator from MFIdentifier to int, so int is the preferred way of expressing this as you can still continue to provide an MFIdentifier if you would like.
